return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      -- lsp
      "clangd",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "elixir-ls",
      "eslint-lsp",
      "gopls",
      "jdtls",
      -- "marksman",
      "neocmakelsp",
      "pyright",
      "ruff-lsp",
      "rust-analyzer",
      "terraform-ls",
      "typescript-language-server",
      "yaml-language-server",
      "vue-language-server",
      "wgsl-analyzer",
      "zls",
      -- "nil",
      -- "nginx-language-server",
      "jsonld-lsp",
      "kcl",
      -- "helm-ls",
      "html-lsp",
      "unocss-language-server",
      "css-lsp",
      "sqlls",
      "lemminx",

      -- DAP
      "codelldb",
      "debugpy",
      "delve",
      "elixir-ls",
      "java-test",
      "java-debug-adapter",
      "js-debug-adapter",
      "kotlin-debug-adapter",
      "firefox-debug-adapter",

      -- Linter
      "cmakelang",
      "cmakelint",
      "hadolint",
      -- "markdownlint",
      "eslint_d",
      "ruff",
      "yamllint",

      -- Formatter
      "stylua",
      "shfmt",
      "black",
      "jq",
      "gofumpt",
      "goimports",
      "gomodifytags",
      "prettierd",
      "xmlformatter",
    },
  },
}
